name: my-CICD!
on:
  push:
    branches:
    - main #指定那个分支在push时触发
jobs: # 触发的任务列表
  # my-build-and-deploy: # 任务1 （可以多个任务）
  job1: # 任务1 （可以多个任务）
    runs-on: ubuntu-latest #字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。
    # ubuntu-latest，ubuntu-18.04或ubuntu-16.04
    # windows-latest，windows-2019或windows-2016
    # macOS-latest或macOS-10.14
    # strategy: #策略 配置16 14  12三个版本node 执行测试
    #   matrix:
    #     node-version: [16.x, 14.x, 12.x]
    steps: #步骤
    - name: 获取源码 #步骤1 下载源码到虚拟机
      uses: actions/checkout@v1 #  这个是github封装好的
    - name: 打包和部署 # 步骤2 打包部署
      # uses: JamesIves/github-pages-deploy-action@master  #
      uses: actions/setup-node@v1 # 当前虚拟机安装node
      with: # 指定node版本 不指定使用默认版本
        node-version: '14.x'
      env: #该步骤所需的环境变量。分别为： GitHub 密钥、发布分支、构建成果所在目录、构建脚本
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages #打包后的分支
        FOLDER: dist #打包后的文件夹名称
        # BUILD_SCRIPT: yarn && yarn build
        BUILD_SCRIPT: npm install && npm run build #打包
    - run:
        # npm install
        # npm run build --if-persist
        # npm testss
        echo: # 输出打印内容
          node -v